// <auto-generated />
namespace TimeSheetGistics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updatedrelations3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedrelations3));
        
        string IMigrationMetadata.Id
        {
            get { return "201210221707365_updated-relations3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
