// <auto-generated />
namespace TimeSheetGistics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class gravatarnamechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gravatarnamechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201210280839191_gravatar-name-change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
