// <auto-generated />
namespace TimeSheetGistics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TimeCardCardDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeCardCardDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201210261002086_TimeCard-CardDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
