// <auto-generated />
namespace TimeSheetGistics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class companybranchuseraddproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(companybranchuseraddproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201210272209136_companybranchuser-add-properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
