// <auto-generated />
namespace TimeSheetGistics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updateids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateids));
        
        string IMigrationMetadata.Id
        {
            get { return "201210160603432_update-ids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
