// <auto-generated />
namespace TimeSheetGistics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class branchmandatory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(branchmandatory));
        
        string IMigrationMetadata.Id
        {
            get { return "201210161123311_branch-mandatory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
