// <auto-generated />
namespace TimeSheetGistics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updatecompanyname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecompanyname));
        
        string IMigrationMetadata.Id
        {
            get { return "201210160514213_update-company-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
